config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
   authenticated :user do
     root 'links#index', as: :authenticated_root
   end

   unauthenticated do
     root 'devise/registrations#new', as: :unauthenticated_root
   end
  end

  resources :links

  get '/:slug' => 'visits#create'

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  validates :slug, :target_url, presence: true
  has_many :visits

  def standardize_target_url!
    target_url.gsub!("http://", "")
    target_url.gsub!("https://", "")
  end

  def visit_count
    visits.count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user
      @links = Link.where(user_id: current_user.id)
    else
      render "index"
    end
  end

  def new
    @link = Link.new
    render "new"
  end

  def show
    @link = Link.find_by(id: params[:id])
  end

  def create
    @link = Link.new(
      user_id: current_user.id,
      slug: params[:slug],
      target_url: params[:target_url]
    )
    @link.standardize_target_url!

      @link.save
      if @link.valid?
        flash[:success] = "link is created !"
        redirect_to links_path
      else
        flash[:danger] = @link.errors.full_messages
        render "new.html.erb"
      end
    # else
    #   flash[:danger] = "you need to log in !"
    #   redirect_to '/users/sign_in'
    # end
  end

  def edit
    @link = Link.find_by(id: params[:id])
  end

  def update
    @link = Link.find_by(id: params[:id])
    @link.update(
      slug: params[:slug],
      target_url: params[:target_url]
    )
    if @link.valid?
      @link.standardize_target_url!
      flash[:success] = "link is updated !"
      redirect_to links_path
    else
      flash[:danger] = @link.errors.full_messages
      render "edit.html.erb"
    end
  end

  def destroy
    @link = Link.find_by(:id => params[:id])
    if @link.destroy
      flash[:success] = "a record has been deleted"
      redirect_to links_path
    else
      flash[:danger] = "unknown mistake"
      redirect_to links_path
    end
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def create
    @link = Link.find_by(slug: params[:slug])
    visit = Visit.new(
      link_id: @link.id,
      ip_address: request.remote_ip
    )
    visit.save
    if @link
      redirect_to "http://#{@link.target_url}"
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShortenurlApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= links_path %>">URL Shorten</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Backstage <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><a href="<%= new_link_path %>">create a new link</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li><a href="#">Something else here</a></li>
              <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%  if current_user  %>
        <li><a href="<%= links_path %>">Welcome, Dear user <%= current_user.email  %> !</a></li>
        <% else %>
        <li><a href="/users/sign_up">Welcome, Dear guest ! Please sign up or log in !</a></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if !current_user %>
              <li><a href="/users/sign_in">Log In</a></li>
              <li><a href="/users/sign_up">Sign Up</a></li>
            <% end %>
            <% if current_user %>
              <li><a href="/users/sign_out">Sign Out</a></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><a href="/users/edit">Edit profile</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if flash.is_a?(Array) %>
  <div id="error_explanation">
    <h2><%= pluralize(@link.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @link.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


  <% flash.each do |name, message| %>
    <div class="alert alert-<%= name %> alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <% if message.is_a?(Array) %>
          <% message.each do |msg| %>
              <ul>
                  <li> <%= msg %>  </li>
              </ul>
          <% end %>
        <% else %>
          <%= message %>
        <% end %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<h1>Please update your link:</h1>

<%= form_tag("/links/#{@link.id}", method: :patch) do %>
<ul>
  <li>
    <%=  label_tag(:slug)%>
    <%= text_field_tag(:slug) %>
  </li>
  <li>
    <%=  label_tag(:target_url)%>
    <%= text_field_tag(:target_url) %>
  </li>
</ul>
  <%= submit_tag("update!") %>
<% end %>

app/views/links/index.html.erb
<h2>Dear user, hit links on slug to go to your target website!</h1>
<br>
<br>


<table>

  <table class="table">
    <thead >
      <tr class="bg-info">
        <th>#</th>
        <th>Slug</th>
        <th>Details</th>
        <th>Created at</th>
      </tr>
    </thead>

    <% if  !@links || @links.count == 0  %>
      <h3> You have no links yet!</h3>

    <% else %>

    <tbody>
      <% @links.each do |link| %>
          <tr>
            <th scope="row">1</th>
              <td><a href="/<%= link.slug %>"><%= link.slug %></a></td>
              <td>
                 <div class="btn-group" role="group" aria-label="...">
                   <a href="/links/<%= link.id %>" class="btn btn-primary" role="button" >details</a>
                   <a href="/links/<%= link.id %>/edit" class="btn btn-warning" role="button" >edit</a>
                   <%= link_to "delete", "/links/#{link.id}" ,method: :delete ,class: "block-link"%>
                  </div>
              </td>
              <td><%= link.created_at %></td>
          </tr>

      <% end %>
   <% end %>

    </tbody>
  </table>

  <div>
    <a href="/links/new" class="btn btn-info" role="button" >Add a new link</a>
  </div>

app/views/links/new.html.erb
<h1>Please add a new link:</h1>

<%= form_tag("/links", method: :post) do %>
<ul>
  <li>
    <%=  label_tag(:user_id)%>
    <%= text_field_tag(:user_id) %>
  </li>
  <li>
    <%=  label_tag(:slug)%>
    <%= text_field_tag(:slug) %>
  </li>
  <li>
    <%=  label_tag(:target_url)%>
    <%= text_field_tag(:target_url) %>
  </li>
</ul>
  <%= submit_tag("create!") %>
<% end %>

<% if @link.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@link.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @link.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/links/show.html.erb
<h1>Link Stats for <%= @link.slug%></h1>
<h3>Visits: <%= @link.visit_count %></h3>
<h4>Target Url: <%= @link.target_url %></h4>